---
backend:
  api_port: 5684
  secret: 'YOUR_SECRET_HERE'
  token_expiry: '1800s'
core:
  host: 'localhost'
  log_level: 'debug'
  socket_port: 1337
database:
  database: upaas
  host: localhost
  password: password1234
  port: 3306
  username: upaasuser
services_directory: '../upaas_services'
token: 'YOUR_TOKEN_HERE'
